[project]
name = "nba-stats-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scikit-learn",
    "mlflow>2.0,<3.0",
    "Flask",
    "streamlit",
    "nba-api",
    "tqdm",
    "hyperopt",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "matplotlib",
    "ipykernel",
]
