[tool.poetry]
name = "frontend-fetch"
version = "0.1.0"
description = ""
authors = ["vykuang <vykuang92@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.8"
nba-api = "^1.1.11"

[tool.poetry.group.dev.dependencies]
